import {
  Brain,
  Globe,
  Calculator,
  GraduationCap,
  Route,
  Mic,
  CheckSquare,
  Instagram,
  TrendingUp,
  Zap,
  Users,
  Gamepad2,
  Cpu,
  ListTodo,
  UserMinus,
} from "lucide-react"
import { type ProjectData } from "@/components/project-modal"

export const projects: ProjectData[] = [
  {
    id: "sway-ai",
    icon: Brain,
    title: "AI Prompt Studio Platform",
    company: "Sway AI",
    description:
      "Engineered comprehensive prompt studio tools enabling dynamic prompt generation and fine-tuning for LLM applications. Integrated RAG systems with LLaMA models via LangChain and FastAPI.",
    longDescription:
      "Led the development of an innovative AI-powered document intelligence platform that revolutionizes how businesses process contracts, invoices, and other critical documents. The platform combines advanced prompt engineering tools with robust RAG (Retrieval-Augmented Generation) systems to deliver unprecedented accuracy and speed in document processing workflows.",
    impact: "Revolutionized AI application development workflow",
    technologies: [
      "LangChain",
      "FastAPI",
      "LLaMA",
      "RAG Systems",
      "Python",
      "React",
      "TypeScript",
      "PySpark",
      "MongoDB",
    ],
    metrics: ["Dynamic Prompt Generation", "LLM Integration", "RAG Optimization"],
    color: "from-purple-500 to-pink-500",
    images: ["/projects/sway-ai-document-intelligence.webp"],
    timeline: "Spring 2024 - Present",
    teamSize: "Individual contributor",
    keyFeatures: [
      "Dynamic prompt generation and fine-tuning capabilities",
      "Integrated LLaMA models via LangChain framework",
      "Advanced RAG system for enhanced document understanding",
      "Real-time document processing with high accuracy",
      "Pivot table widget features with front-end/back-end coordination",
      "PySpark analytics workflows with quantile analysis and winsorization",
      "MongoDB aggregation pipelines for complex data transformation",
    ],
    challenges: [
      "Optimizing prompt generation for diverse document types and use cases",
      "Implementing efficient RAG systems that balance accuracy with performance",
      "Designing scalable architecture to handle enterprise-level document volumes",
    ],
    outcomes: [
      "Achieved 95% accuracy in document classification and extraction",
      "Reduced document processing time by 80% compared to manual methods",
      "Successfully deployed to production serving multiple enterprise clients",
    ],
    demoUrl: "https://sway-ai.com",
    category: "AI/ML",
  },
  {
    id: "react-calculator",
    icon: Calculator,
    title: "React JS Calculator",
    company: "Personal Project",
    description:
      "A fully functional calculator web application built with React, featuring basic arithmetic operations with a clean, responsive user interface.",
    longDescription:
      "Developed a modern calculator application using React.js that demonstrates proficiency in component-based architecture and state management. The calculator handles all basic arithmetic operations with proper error handling and a responsive design that works seamlessly across devices.",
    impact: "Demonstrates modern React development skills",
    technologies: ["React.js", "JavaScript", "CSS3", "HTML5", "Responsive Design"],
    metrics: ["Live Application", "Responsive Design", "Clean UI"],
    color: "from-blue-500 to-blue-700",
    images: ["/projects/calculator-screenshot.png"],
    timeline: "Personal Project",
    teamSize: "Individual contributor",
    keyFeatures: [
      "Basic arithmetic operations (addition, subtraction, multiplication, division)",
      "Clean and intuitive user interface",
      "Responsive design for all screen sizes",
      "Real-time calculation display",
      "Error handling for invalid operations",
      "Modern React hooks implementation",
    ],
    challenges: [
      "Implementing proper state management for calculation history",
      "Handling edge cases and mathematical errors",
      "Creating a responsive design that works on all devices",
    ],
    outcomes: [
      "Successfully deployed and publicly accessible",
      "Demonstrates React component architecture best practices",
      "Serves as a portfolio piece showcasing frontend development skills",
    ],
    demoUrl: "http://app.shayanys.com/calculator/",
    category: "Web Application",
  },
  {
    id: "masters-thesis",
    icon: Gamepad2,
    title: "AI Game Quest Generator",
    company: "Brock University",
    description:
      "Master's thesis project: 'A Game with Auto Generating Quests Using Genetic Programming' - Novel approach to procedural content generation in games using evolutionary algorithms.",
    longDescription:
      "Conducted comprehensive research on procedural content generation in video games, focusing on quest generation using genetic programming. The project involved developing algorithms that can automatically create engaging and balanced quests for players, demonstrating the practical application of AI in game design. The work contributes to the growing field of procedural content generation and AI-driven game development.",
    impact: "Advanced the field of procedural content generation",
    technologies: [
      "Genetic Programming",
      "Machine Learning",
      "Game Development",
      "Python",
      "AI Algorithms",
    ],
    metrics: ["Academic Publication", "Novel AI Approach", "Game Design Innovation"],
    color: "from-green-500 to-emerald-700",
    images: ["/projects/auto-generated-RPG-quests-Gemini-generated.png"],
    timeline: "2017 - 2019",
    teamSize: "Individual researcher",
    keyFeatures: [
      "Genetic programming algorithms for quest generation",
      "Dynamic difficulty adjustment based on player performance",
      "Procedural narrative generation",
      "Multi-objective optimization for quest balance",
      "Integration with existing game engines",
      "Performance evaluation and testing framework",
    ],
    challenges: [
      "Balancing computational complexity with real-time performance",
      "Creating meaningful and engaging quest narratives",
      "Developing evaluation metrics for procedurally generated content",
    ],
    outcomes: [
      "Successfully defended thesis and graduated with Master's degree",
      "Contributed novel approach to procedural content generation",
      "Demonstrated practical application of AI in game development",
    ],
    category: "AI/ML",
  },
  {
    id: "vrptw-ga",
    icon: Cpu,
    title: "Vehicle Routing Optimization",
    company: "Open Source Project",
    description:
      "Implementation of genetic algorithm to solve Vehicle Routing Problem with Time Windows (VRPTW) - demonstrates understanding of complex optimization problems.",
    longDescription:
      "Developed a sophisticated genetic algorithm solution for the Vehicle Routing Problem with Time Windows, one of the most challenging optimization problems in logistics and transportation. The project showcases advanced algorithmic thinking and optimization techniques, with practical applications in delivery services, supply chain management, and logistics planning.",
    impact: "Solves complex logistics optimization problems",
    technologies: ["Genetic Algorithm", "Python", "C++", "Optimization", "Data Structures"],
    metrics: ["Multi-objective Optimization", "Constraint Handling", "Performance Analysis"],
    color: "from-orange-500 to-red-700",
    images: ["/projects/VRPTW-ChatGPT-generated.png"],
    timeline: "Academic Project",
    teamSize: "Individual contributor",
    keyFeatures: [
      "Genetic algorithm implementation with custom operators",
      "Time window constraint handling",
      "Multi-objective optimization (distance, time, capacity)",
      "Performance benchmarking against standard datasets",
      "Visualization of optimal routes",
      "Scalable solution for large problem instances",
    ],
    challenges: [
      "Handling multiple constraints simultaneously",
      "Balancing exploration and exploitation in genetic algorithm",
      "Optimizing algorithm performance for large-scale problems",
    ],
    outcomes: [
      "Successfully implemented and tested on benchmark problems",
      "Achieved competitive results compared to existing solutions",
      "Open-sourced for academic and research use",
    ],
    demoUrl: "https://github.com/shayan-ys/VRPTW-ga",
    category: "AI/ML",
  },
  {
    id: "alexa-random-teller",
    icon: Mic,
    title: "Alexa Skill: Random Teller",
    company: "Amazon Alexa Store",
    description:
      "Published Alexa skill that provides random facts, jokes, and interesting information through voice interaction, demonstrating voice UI development skills.",
    longDescription:
      "Developed and published a comprehensive Alexa skill that engages users with random facts, jokes, and interesting information. The skill showcases proficiency in voice user interface design, natural language processing, and cloud-based application development using Amazon's ecosystem. The project demonstrates understanding of conversational AI and user experience design for voice interactions.",
    impact: "Published on Amazon Alexa Store",
    technologies: [
      "Amazon Alexa Skills Kit",
      "AWS Lambda",
      "Node.js",
      "Voice UI",
      "Natural Language Processing",
    ],
    metrics: ["Voice Interaction", "Dynamic Content", "Cloud Deployment"],
    color: "from-indigo-600 to-blue-600",
    images: ["/projects/alexa-random-teller-screenshot.png"],
    timeline: "Published Project",
    teamSize: "Individual contributor",
    keyFeatures: [
      "Voice-activated random fact delivery",
      "Dynamic content generation",
      "Natural language understanding",
      "Multi-category content (facts, jokes, trivia)",
      "Engaging conversational flow",
      "Cloud-based serverless architecture",
    ],
    challenges: [
      "Designing intuitive voice user interfaces",
      "Handling various speech patterns and accents",
      "Creating engaging conversational experiences",
    ],
    outcomes: [
      "Successfully published on Amazon Alexa Store",
      "Demonstrates voice application development skills",
      "Gained experience with AWS cloud services and serverless architecture",
    ],
    demoUrl: "https://www.amazon.ca/Shayan-Ys-Random-Teller/dp/B07ZCZ2YQ9/",
    category: "Voice Assistant",
  },
  {
    id: "todo-app",
    icon: ListTodo,
    title: "Todo ReactJS",
    company: "Personal Project",
    description:
      "A simple but effective todo list application with persistent storage, featuring add, edit, and delete functionality with a clean user interface.",
    longDescription:
      "Built a comprehensive todo list application that demonstrates proficiency in frontend development, state management, and local storage implementation. The application provides a clean, intuitive interface for task management with persistent data storage, showcasing practical web development skills and user experience design.",
    impact: "Demonstrates full-stack web development skills",
    technologies: ["JavaScript", "HTML5", "CSS3", "LocalStorage", "Responsive Design"],
    metrics: ["Task Management", "Persistent Storage", "User Experience"],
    color: "from-green-500 to-green-700",
    images: ["/projects/todo-list-screenshot.png"],
    timeline: "Personal Project",
    teamSize: "Individual contributor",
    keyFeatures: [
      "Add, edit, and delete tasks",
      "Persistent storage using LocalStorage",
      "Task completion tracking",
      "Responsive design for all devices",
      "Clean and intuitive user interface",
      "Real-time updates and feedback",
    ],
    challenges: [
      "Implementing reliable local storage mechanism",
      "Creating smooth user interactions and animations",
      "Ensuring data persistence across browser sessions",
    ],
    outcomes: [
      "Successfully deployed and publicly accessible",
      "Demonstrates practical web development skills",
      "Serves as a foundation for more complex project management applications",
    ],
    demoUrl: "http://app.shayanys.com/todo/",
    category: "Web Application",
  },
  {
    id: "instagram-tool",
    icon: UserMinus,
    title: "Instagram Non-Followers Tool",
    company: "Personal Project",
    description:
      "A JavaScript tool that helps users identify Instagram accounts that don't follow back, demonstrating API integration and social media analytics.",
    longDescription:
      "Developed a web-based tool that analyzes Instagram follow relationships to help users identify accounts that don't follow back. The project showcases API integration skills, data processing capabilities, and practical application development for social media management. The tool provides valuable insights for social media strategy and follower management.",
    impact: "Provides valuable social media insights",
    technologies: [
      "JavaScript",
      "Instagram API",
      "Data Processing",
      "Web APIs",
      "Social Media Analytics",
    ],
    metrics: ["API Integration", "Data Analysis", "Social Media Management"],
    color: "from-purple-600 to-pink-600",
    images: ["/projects/instagram-non-followers-screenshot.png"],
    timeline: "Personal Project",
    teamSize: "Individual contributor",
    keyFeatures: [
      "Instagram API integration",
      "Follow relationship analysis",
      "User-friendly interface for data visualization",
      "Export functionality for results",
      "Privacy-focused data handling",
      "Real-time analysis and reporting",
    ],
    challenges: [
      "Working with Instagram's API limitations and restrictions",
      "Handling large datasets efficiently",
      "Ensuring user privacy and data security",
    ],
    outcomes: [
      "Successfully deployed and publicly accessible",
      "Demonstrates API integration and data processing skills",
      "Provides practical utility for social media management",
    ],
    demoUrl: "http://app.shayanys.com/insta-non-followers/",
    category: "Social Media Tool",
  },
  {
    id: "oanda-currency-converter",
    icon: Globe,
    title: "Currency Converter Web App",
    company: "OANDA Corporation",
    description:
      "Led complete redevelopment of high-traffic currency converter using React, Flask microservices, and Google Kubernetes Engine. Achieved exceptional performance and scalability.",
    longDescription:
      "Spearheaded the complete architectural redesign and redevelopment of OANDA's flagship currency converter application. This mission-critical application serves over 500,000 daily users and handles 35 million monthly visits across the platform. The project involved migrating from legacy systems to a modern, cloud-native architecture built on React, Flask microservices, and Google Kubernetes Engine.",
    impact: "500K daily visits, 35M monthly visits across platform",
    technologies: ["React", "Flask", "GKE", "Microservices", "Python", "TypeScript", "Docker"],
    metrics: ["500K Daily Visits", "35M Monthly Visits", "High Availability"],
    color: "from-blue-500 to-cyan-500",
    images: ["/projects/oanda-currency-converter.png"],
    timeline: "Spring 2020 - Winter 2024",
    teamSize: "6 engineers (team lead)",
    keyFeatures: [
      "Real-time currency conversion with live exchange rates",
      "Support for all major world currencies",
      "Responsive design optimized for mobile and desktop",
      "High-performance caching layer for sub-second response times",
      "Microservices architecture for scalability",
      "Advanced analytics and monitoring",
    ],
    challenges: [
      "Handling massive traffic loads with 99.9% uptime requirements",
      "Implementing real-time data synchronization across multiple services",
      "Optimizing performance for sub-second response times under heavy load",
    ],
    outcomes: [
      "Achieved 99.9% uptime with zero data loss during migration",
      "Improved page load speeds by 60% compared to legacy system",
      "Successfully scaled to handle traffic spikes during market volatility",
    ],
    demoUrl: "https://oanda.com/currency/converter",
    category: "Web Application",
  },
  {
    id: "oanda-data-visualization",
    icon: TrendingUp,
    title: "Data Visualization Suite",
    company: "OANDA Corporation",
    description:
      "Developed and deployed six React-based data visualization applications for internal use, significantly improving operational efficiency and reducing infrastructure costs.",
    longDescription:
      "Created a comprehensive suite of internal data visualization tools that transformed how OANDA's teams analyze and interact with complex financial data. These applications provide real-time insights into trading patterns, market trends, and operational metrics, enabling data-driven decision making across the organization.",
    impact: "$400K annual cost savings through internal tooling",
    technologies: ["React", "D3.js", "Chart.js", "Python", "Data Visualization", "Internal Tools"],
    metrics: ["$400K Cost Savings", "6 Applications", "Team Productivity"],
    color: "from-green-500 to-emerald-500",
    images: ["/projects/oanda-data-vis.png"],
    timeline: "Spring 2021 - Winter 2023",
    teamSize: "6 engineers (team lead)",
    keyFeatures: [
      "Interactive real-time dashboards for financial data",
      "Advanced charting capabilities with D3.js",
      "Custom data filtering and aggregation tools",
      "Automated report generation and scheduling",
      "Role-based access control for sensitive data",
      "Export capabilities for presentations and analysis",
    ],
    challenges: [
      "Processing and visualizing large volumes of real-time financial data",
      "Creating intuitive interfaces for complex analytical workflows",
      "Ensuring data security and compliance with financial regulations",
    ],
    outcomes: [
      "Eliminated need for expensive third-party analytics tools",
      "Improved decision-making speed by 40% through better data access",
      "Enhanced data accuracy and reduced manual reporting errors by 85%",
    ],
    category: "Data Analytics",
  },
  {
    id: "oanda-embeddable-app",
    icon: Zap,
    title: "NextJS Embeddable App",
    company: "OANDA Corporation",
    description:
      "Engineered a NextJS embeddable application with 300K monthly views, deployed with CI/CD via CircleCI and ArgoCD on Kubernetes infrastructure.",
    longDescription:
      "Developed a high-performance embeddable application using NextJS that serves 300,000 monthly views. The application was designed to be seamlessly integrated into partner websites and third-party platforms, providing real-time financial data and interactive features while maintaining consistent performance and reliability.",
    impact: "300K monthly views with high reliability",
    technologies: ["NextJS", "React", "TypeScript", "CircleCI", "ArgoCD", "Kubernetes", "Docker"],
    metrics: ["300K Monthly Views", "CI/CD Pipeline", "High Reliability"],
    color: "from-indigo-500 to-blue-500",
    images: ["/projects/nextjs-embedded-app-Chatgpt-generated.png"],
    timeline: "Spring 2021 - Winter 2023",
    teamSize: "Individual contributor",
    keyFeatures: [
      "Seamless embedding capabilities for partner websites",
      "Real-time data synchronization and updates",
      "Responsive design for all device types",
      "Automated CI/CD pipeline with CircleCI",
      "Kubernetes deployment with ArgoCD",
      "Performance optimization for embedded environments",
    ],
    challenges: [
      "Ensuring consistent performance across different embedding contexts",
      "Implementing robust CI/CD pipeline for reliable deployments",
      "Optimizing bundle size for faster loading in embedded scenarios",
    ],
    outcomes: [
      "Achieved 300K monthly views with 99.9% uptime",
      "Reduced deployment time by 70% through automated CI/CD",
      "Successfully integrated with multiple partner platforms",
    ],
    category: "Web Application",
  },
  {
    id: "yektanet-ad-platform",
    icon: Users,
    title: "Iran's Largest Ad Platform",
    company: "Yektanet",
    description:
      "Co-created highly-available, load-balancing advertising platform with comprehensive Python Django suite including big-data analytics and specialized dashboards for different user types.",
    longDescription:
      "Co-architected and developed Iran's most successful online advertising platform from the ground up. This comprehensive platform includes sophisticated load balancing, real-time bidding capabilities, advanced analytics, and multiple specialized dashboards tailored for advertisers, publishers, and platform administrators.",
    impact: "Became Iran's largest online advertising platform",
    technologies: ["Python", "Django", "Big Data", "Load Balancing", "Analytics", "PostgreSQL"],
    metrics: ["Largest Platform", "High Availability", "Multi-Dashboard"],
    color: "from-orange-500 to-red-500",
    images: ["/projects/yektanet-dashbard.png"],
    timeline: "Spring 2016 - Spring 2018",
    teamSize: "8+ engineers (co-architect)",
    keyFeatures: [
      "Real-time bidding and auction system",
      "Advanced targeting and segmentation capabilities",
      "Comprehensive analytics and reporting suite",
      "Multi-tenant dashboard architecture",
      "Automated campaign optimization",
      "Fraud detection and prevention systems",
    ],
    challenges: [
      "Building a scalable platform to handle millions of ad requests per day",
      "Implementing real-time bidding with sub-millisecond response times",
      "Creating robust fraud detection to maintain platform integrity",
    ],
    outcomes: [
      "Captured 60% market share in Iran's digital advertising space",
      "Processed over 10 million ad requests daily at peak",
      "Generated significant revenue growth for both advertisers and publishers",
    ],
    demoUrl: "https://yektanet.com",
    category: "AdTech Platform",
  },
  {
    id: "hostpapa-payments",
    icon: Users,
    title: "Payment Integration Systems",
    company: "HostPapa",
    description:
      "Successfully integrated AliPay and PayPal recurring billing systems into existing infrastructure, facilitating major business acquisitions and improving customer retention.",
    longDescription:
      "Led the strategic integration of multiple payment systems including AliPay and PayPal recurring billing into HostPapa's existing Ubersmith infrastructure. This initiative was crucial for expanding into Asian markets and improving the overall customer payment experience, directly contributing to successful business acquisitions.",
    impact: "Enabled acquisition of 1500+ customers, 15% renewal increase",
    technologies: ["Payment Integration", "AliPay", "PayPal", "Billing Systems", "PHP", "MySQL"],
    metrics: ["1500+ Customers", "15% Renewal Increase", "Business Growth"],
    color: "from-indigo-500 to-purple-500",
    images: ["/projects/hostpapa-paypal.png"],
    timeline: "Spring 2018 - Spring 2020",
    teamSize: "3 engineers",
    keyFeatures: [
      "Seamless AliPay integration for Asian market expansion",
      "PayPal recurring billing for subscription management",
      "Multi-currency support and conversion",
      "Automated billing reconciliation",
      "Fraud detection and chargeback prevention",
      "Customer self-service payment portal",
    ],
    challenges: [
      "Integrating with legacy Ubersmith billing system without disruption",
      "Ensuring PCI compliance across multiple payment processors",
      "Handling currency conversion and international payment regulations",
    ],
    outcomes: [
      "Successfully acquired 1,500-customer company through AliPay integration",
      "Increased service renewal rates by 15% through improved payment UX",
      "Expanded market reach into Asian territories with localized payment options",
    ],
    category: "Payment Systems",
  },
  {
    id: "chetor-performance",
    icon: TrendingUp,
    title: "Performance Optimization Suite",
    company: "Chetor",
    description:
      "Developed specialized WordPress plugins and themes using advanced optimization techniques including lazy-loading and responsive images to dramatically improve site performance.",
    longDescription:
      "Created a comprehensive performance optimization suite for WordPress websites, focusing on dramatically improving page load speeds and user experience. The project involved developing custom plugins and themes with advanced techniques including intelligent lazy-loading, responsive image optimization, and efficient caching strategies.",
    impact: "45% improvement in page load speed",
    technologies: [
      "WordPress",
      "Performance Optimization",
      "Lazy Loading",
      "Responsive Design",
      "PHP",
    ],
    metrics: ["45% Speed Improvement", "Custom Plugins", "User Experience"],
    color: "from-teal-500 to-blue-500",
    images: ["/projects/chetor.png"],
    timeline: "Winter 2016 - Summer 2017",
    teamSize: "2 engineers",
    keyFeatures: [
      "Advanced lazy-loading implementation for images and content",
      "Responsive image optimization with multiple breakpoints",
      "Custom WordPress plugins for performance enhancement",
      "Intelligent caching strategies for dynamic content",
      "CSS and JavaScript minification and bundling",
      "Database query optimization for faster page loads",
    ],
    challenges: [
      "Optimizing performance while maintaining WordPress compatibility",
      "Implementing lazy-loading without affecting SEO rankings",
      "Balancing image quality with loading speed across devices",
    ],
    outcomes: [
      "Achieved 45% improvement in average page load times",
      "Improved Core Web Vitals scores across all optimized sites",
      "Enhanced user engagement with reduced bounce rates",
    ],
    demoUrl: "https://chetor.com",
    category: "Performance Optimization",
  },
]

export const categories = [
  "All Projects",
  "AI/ML",
  "Web Application",
  "Data Analytics",
  "Voice Assistant",
  "AdTech Platform",
  "Payment Systems",
  "Social Media Tool",
  "Enterprise",
]

// Top 6 most valuable projects for homepage (based on 2025 hiring trends)
export const featuredProjects: ProjectData[] = [
  // 1. AI Prompt Studio Platform - Most valuable for 2025 AI revolution
  projects.find((p) => p.id === "sway-ai")!,
  // 2. Vehicle Routing Optimization - Advanced algorithms & optimization
  projects.find((p) => p.id === "vrptw-ga")!,
  // 3. Currency Converter - High-scale production system
  projects.find((p) => p.id === "oanda-currency-converter")!,
  // 4. Data Visualization Suite - Data analytics in high demand
  projects.find((p) => p.id === "oanda-data-visualization")!,
  // 5. AI Game Quest Generator - AI research and innovation
  projects.find((p) => p.id === "masters-thesis")!,
  // 6. NextJS Embeddable App - Modern web technologies
  projects.find((p) => p.id === "oanda-embeddable-app")!,
]
